version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/MovieApp
   overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
  # AfterInstall:
  #  - location: scripts/install_app_dependencies
  #    timeout: 300
  #    runas: root
  # ApplicationStart:
  #  - location: scripts/start_server
  #    timeout: 300
  #    runas: root